-- Add missing columns to students table for Student entity model
-- This migration adds all the missing columns that the Student entity expects

-- Add missing columns to students table
ALTER TABLE students 
ADD COLUMN IF NOT EXISTS is_international BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS nationality VARCHAR(50),
ADD COLUMN IF NOT EXISTS passport_number VARCHAR(50),
ADD COLUMN IF NOT EXISTS visa_number VARCHAR(50),
ADD COLUMN IF NOT EXISTS visa_expiry_date DATE,
ADD COLUMN IF NOT EXISTS is_scholarship BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS scholarship_type VARCHAR(100),
ADD COLUMN IF NOT EXISTS scholarship_amount DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS is_financial_aid BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS financial_aid_type VARCHAR(100),
ADD COLUMN IF NOT EXISTS financial_aid_amount DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS has_special_needs BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS special_needs_details TEXT,
ADD COLUMN IF NOT EXISTS is_boarding BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS boarding_house VARCHAR(100),
ADD COLUMN IF NOT EXISTS room_number VARCHAR(20),
ADD COLUMN IF NOT EXISTS bed_number VARCHAR(20),
ADD COLUMN IF NOT EXISTS transport_required BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS transport_route VARCHAR(100),
ADD COLUMN IF NOT EXISTS pickup_point VARCHAR(200),
ADD COLUMN IF NOT EXISTS drop_point VARCHAR(200),
ADD COLUMN IF NOT EXISTS medical_conditions TEXT,
ADD COLUMN IF NOT EXISTS allergies TEXT,
ADD COLUMN IF NOT EXISTS medications TEXT,
ADD COLUMN IF NOT EXISTS doctor_name VARCHAR(100),
ADD COLUMN IF NOT EXISTS doctor_phone VARCHAR(20),
ADD COLUMN IF NOT EXISTS hospital_preference VARCHAR(200),
ADD COLUMN IF NOT EXISTS insurance_provider VARCHAR(100),
ADD COLUMN IF NOT EXISTS insurance_policy_number VARCHAR(100),
ADD COLUMN IF NOT EXISTS previous_school VARCHAR(200),
ADD COLUMN IF NOT EXISTS previous_grade VARCHAR(20),
ADD COLUMN IF NOT EXISTS transfer_date DATE,
ADD COLUMN IF NOT EXISTS graduation_date DATE,
ADD COLUMN IF NOT EXISTS enrollment_number VARCHAR(50),
ADD COLUMN IF NOT EXISTS roll_number VARCHAR(20);
