-- Add missing columns to academic_years table
ALTER TABLE academic_years 
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS academic_calendar TEXT,
ADD COLUMN IF NOT EXISTS holidays TEXT,
ADD COLUMN IF NOT EXISTS exam_schedule TEXT,
ADD COLUMN IF NOT EXISTS registration_deadline DATE,
ADD COLUMN IF NOT EXISTS enrollment_deadline DATE,
ADD COLUMN IF NOT EXISTS graduation_date DATE,
ADD COLUMN IF NOT EXISTS is_current BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS notes TEXT;

-- Add missing columns to terms table
ALTER TABLE terms 
ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'PENDING',
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS is_current BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS notes TEXT;

-- Add missing columns to classes table
ALTER TABLE classes 
ADD COLUMN IF NOT EXISTS room_number VARCHAR(20),
ADD COLUMN IF NOT EXISTS building VARCHAR(50),
ADD COLUMN IF NOT EXISTS floor VARCHAR(10),
ADD COLUMN IF NOT EXISTS capacity INTEGER DEFAULT 40,
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS schedule TEXT,
ADD COLUMN IF NOT EXISTS academic_level VARCHAR(50),
ADD COLUMN IF NOT EXISTS stream VARCHAR(50),
ADD COLUMN IF NOT EXISTS section VARCHAR(10),
ADD COLUMN IF NOT EXISTS semester VARCHAR(20),
ADD COLUMN IF NOT EXISTS academic_program VARCHAR(100),
ADD COLUMN IF NOT EXISTS curriculum_version VARCHAR(20),
ADD COLUMN IF NOT EXISTS start_date DATE,
ADD COLUMN IF NOT EXISTS end_date DATE,
ADD COLUMN IF NOT EXISTS is_online BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS online_platform VARCHAR(100),
ADD COLUMN IF NOT EXISTS online_link TEXT,
ADD COLUMN IF NOT EXISTS notes TEXT;

-- Add missing columns to subjects table
ALTER TABLE subjects 
ADD COLUMN IF NOT EXISTS prerequisites TEXT,
ADD COLUMN IF NOT EXISTS learning_objectives TEXT,
ADD COLUMN IF NOT EXISTS syllabus TEXT,
ADD COLUMN IF NOT EXISTS textbooks TEXT,
ADD COLUMN IF NOT EXISTS reference_materials TEXT,
ADD COLUMN IF NOT EXISTS assessment_methods TEXT,
ADD COLUMN IF NOT EXISTS passing_criteria TEXT,
ADD COLUMN IF NOT EXISTS max_students INTEGER,
ADD COLUMN IF NOT EXISTS min_students INTEGER,
ADD COLUMN IF NOT EXISTS is_compulsory BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS is_theory BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS is_practical BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS is_laboratory BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS is_project_based BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS weekly_hours INTEGER,
ADD COLUMN IF NOT EXISTS theory_hours INTEGER,
ADD COLUMN IF NOT EXISTS practical_hours INTEGER,
ADD COLUMN IF NOT EXISTS laboratory_hours INTEGER,
ADD COLUMN IF NOT EXISTS semester VARCHAR(20),
ADD COLUMN IF NOT EXISTS academic_level VARCHAR(50),
ADD COLUMN IF NOT EXISTS department VARCHAR(100),
ADD COLUMN IF NOT EXISTS faculty VARCHAR(100);
